{% set version = "0.19.15" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 7f8f012d6e2fe9f9883199341e7101d198eb5d583c41aefe08e872985b4f94e4

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.17.2
    - jupyter_client >= 4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.17.2
    - jupyter_client >= 4.3
    - ipykernel

test:
  # Python imports
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: http://github.com/calsto/octave_kernel
  license: BSD
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD


extra:
    recipe-maintainers:
        - blink1073
