{% set version = "0.23.1" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: e582fa41eefc285509725c7018bf76eea7275d3210ecb6f6e9deba2f7e53eaf4

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.18.0ke
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

test:
  # Python imports
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: http://github.com/calsto/octave_kernel
  license: BSD
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD


extra:
    recipe-maintainers:
        - blink1073
