{% set version = "0.28.2" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 1a031d17d5b4a2c36e67e239cdb16655a9095540c1d17fbc975e0c0740f0600a

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.20.7
    - jupyter_client >=4.3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.20.7
    - jupyter_client >=4.3.0
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
