{% set version = "0.19.17" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: e2b1e821a7c86c091cfe97e1af4c4fd7cf27a1c3b37d56a1e618eccb48716493

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.17.4
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.17.4
    - jupyter_client >=4.3
    - ipykernel

test:
  # Python imports
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: http://github.com/calsto/octave_kernel
  license: BSD
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD


extra:
    recipe-maintainers:
        - blink1073
