{% set version = "0.30.1" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 8301bde414b90189458579a41b234a7765eb49bf354fa1d712b5d9fb682dcac8

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - metakernel >=0.22.1
    - jupyter_client >=4.3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.22.1
    - jupyter_client >=4.3.0
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
