{% set version = "0.22.0" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: f2c54337c75acf6a8111da490bf6ba40494fd98956360c9ca911391037c2169b

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

test:
  # Python imports
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: http://github.com/calsto/octave_kernel
  license: BSD
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD


extra:
    recipe-maintainers:
        - blink1073
