{% set version = "0.24.2" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 84c1974278b33f023cb179cde2abf2a4904762f8d90f875bcf7671798a81fbc2

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.18.0ke
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

test:
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
