{% set version = "0.28.0" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: faba73e8df6d98e822e5360f8d2533224447045c0223dae07f362fe7922271ee

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.18.0
    - jupyter_client >=4.3
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
