travis:
  secure:
    BINSTAR_TOKEN: RbJ962lOwBeUNP+NHjMnGucWK7AU5483eDFWsB0PxSbHwSzWTTYgBxTgeihO2QCs2GSs82QDYW5G2bVlbBZU8Q2jvvwqdttFFl4yOaPBmJKVXu9s4VHWHNDSestMHWuULTE874iTz4ShqJfZC8KVm6OejmCOb8BEoLAqBBrhFF64unsUwUCxJr1iDPxDl2Q9kab8DUySF7Fdg3pGkdorvLKeyQQY+tUqMuYFirpED1PQkt8oQQdHG3qM0AwtyV8rUzHJQvQmGO+i6oy+FoKsTQrfiK45P8yvtJ24ePaysigkkMuLkEiYmiGcS+12h1p7ua4jCaPs/tHV8cdi6BqaCP26l7eerGLwgWtK2ND+b3erJsJDFCCqo85TqIaZ2orDlbScyrHQ1R0CHrVo8OFM1mSgjgom5hdGMZts8sJ5W5lQLIyMsLWgDYkh1PHKSp6Kr/ugxS93SCpMbIGMtRC71JarNhGjUVTEn9w3mtdIAuFNIHonnPXSfR46NsGXfWAXTs5vRFOK7vug77pDdbbX5dM0MB+40RQGEp+h+19P+z2870e/JFgo/EGdBKgh/0X4J28r798Gt5FAc5lVq1TC9E8f4UBN0G6JqeHW0TVTla+DR27fxXsE4SStz9Q2ds7Eizc5BpmVBOvvBcJg1Pcg7U+1KO1fVBcOFuvkTZf09C8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
