travis:
  secure:
    BINSTAR_TOKEN: n1N6ibwPt2JMk8XCOvw6jB04rbBzx73a5fTFKbi+7TIU1AWeNurQGgQ/aAOzYE1t8z1kcJ/qRbSm2YXouXewo9l0VnUiPFlDE5qCLS2sUlDJ1/J+QQ9oJckzW6K4rO3NtMmAgR8WBm0AHigAbQIzAuf9tjVqHC85Sy5yQc3aqro5t+Rp4LNd/0iUhPSEmiXUbzsTimLHDIBYIdz1fjofm+q43gGJozkIIKdYFWU1KMjXrkK7Di6rE1cj+cnV+d/bQPNH4jB+GMYliEb75GTZl7npGMlEgz9ww1hKw9LGXkkYCj+/4m3JfVYhe/pNo64uhEJ4nsAOWmBXw51g1GbM18bO/QD71QMuYcexIywP0qXrTycNhO5NVJ/+YlbO0tmULDB6baSZ3lGIatV17sE5BmOja3aAh6g7ZoLYMaPs7+TPk2o7TKt/tFtOoaf1EGoQNRYM9LBKCPGu3P2wKq4PEc6B8FHag2Uqu+MaMV3zEoK4fVibi/YTRnIQEDgtdKnhK1yi0/dkyqaAr32aoXfvOmGA2KJVEa4fMSto5B888d5n7SreVRnVL9v8H0/FOg+8dSdxR0vZfmsQYCL9rQVPsZlqlpiJgThdCLuwmCpw5RYogoTJBa4Vp9rMh2bDRtJh5vko6tZxIyEWfIR57NnOZvbvl2uR8snF9ue0bv7yFM0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
